// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function RenderTemplate(arg1) {
  return window['go']['main']['App']['RenderTemplate'](arg1);
}
