// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListTemplates():Promise<Array<string>>;

export function RenderTemplate(arg1:main.TemplateData):Promise<main.RenderedTemplate>;
